version: "3.8"
services:  
  docker-dotnet:
    build: ./
    tty: true
    stdin_open: true
    ports:
      - 5000:5000
      - 5001:5001
    volumes:
      - ./:/docker-dotnet
      - /bin
      - /obj
    #command: dotnet run
    command: sh -c "tmux new -d -s my_session;
      tmux send-keys -t my_session dotnet Space run C-m;
      tmux attach -t my_session"
